#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#


/bin/echo -n "Testing build..."

if ! make test > .test.out 2>&1; then
    /bin/echo "failure!  Push denied."
    /bin/echo "Check .test.out for details"
    exit 1
else
    /bin/echo "success!"
    exit 0
fi
